services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: order_management
    ports:
      - "3306:3306"
    networks:
      - backend

  order-app:
    build: .
    container_name: order-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
